title: "Able Guide"
url: https://www.markdownguide.org # site url
baseurl: "" # apply repo name if use it under gh-pages branch
getbaseurl: "https://pwcdemoinstance.ddns.net/support/docs/"
env: "Local"

repo: http://github.com/mattcone/markdown-guide
comments: false

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jemoji

collections:
  - basic-syntax
  - extended-syntax

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Author settings
author:
  name     : "Jayand Bharati"

# social settings
og_locale: "en_US"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt", "Rakefile"]
